<?= $this->extend('layout/layout_default') ?>

<?= $this->section('style') ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.12/themes/default/style.min.css" />
<style>
    .jstree-node {
        cursor: pointer;
    }

    .pdf-viewer {
        width: 100%;
        height: 600px;
    }

    .pdf-controls {
        margin-left: 5px;
    }

    .pdf-controls button,
    .pdf-controls a {
        /* margin-right: 10px; */
    }

    #search-input {
        width: 300px;
        padding: 8px;
        font-size: 16px;
        margin-bottom: 10px;
    }

    #year-dropdown {
        height: 38px;
        margin-left: 5px;
    }

    #search-results {
        list-style-type: none;
        padding: 0;
        margin-top: 0px;
        margin-bottom: 0px;
        max-height: 200px;
        background-color: white;
        overflow-y: auto;
    }

    #search-results li {
        cursor: pointer;
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 5px;
        margin-left: 5px;
        margin-right: 5px;

    }

    #search-results li:hover {
        background-color: #f0f0f0;
    }

    #pdf-container {
        position: relative;
    }

    .home {
        margin-left: 5px;
    }

    .submenu {
        overflow-x: auto;
        overflow-y: hidden;
        box-sizing: content-box;
        -webkit-overflow-scrolling: touch;
        position: absolute;
        top: 0;
        left: 0;
        z-index: 1;
        /* Pastikan submenu berada di atas pdf-viewer */
        background-color: #fff;
        /* Memberi latar belakang putih untuk submenu */
        padding: 10px;
        padding-bottom: 20px;
        border: 1px solid #ccc;
        height: 37px;
        display: flex;
        width: calc(100% - 22px);
    }

    #pdf-viewer {
        margin-top: 70px;
        /* Tetapkan gaya lain yang Anda inginkan untuk pdf-viewer */
    }

    .tbdownload {
        backface-visibility: hidden;
        position: relative;
        cursor: pointer;
        display: inline-block;
        background: linear-gradient(180deg, #94d9be 0%, #60b091 98.87975011670068%);
        border-radius: 3px;
        border: 1px solid #4dd070;
        border-width: 1px 1px 1px 1px;
        padding: 5px 15px 5px 15px;
        color: #fff;
        font-size: 12px;
        font-weight: 400;
        height: 38px;
    }

    .tbdownload:hover {
        background: linear-gradient(180deg, #60b091 0%, #99b091 98.87975011670068%);
    }

    .result {
        border: 1px solid #ccc;
        position: absolute;
        top: 54px;
        left: 0;
        z-index: 999;
        margin-bottom: 20px;
    }
</style>
<?= $this->endSection() ?>

<?= $this->section('konten') ?>
<div id="pdf-container">
    <div class="submenu">
        <div class="searching">
            <input type="text" id="search-input" placeholder="Cari Provinsi atau Kota">
        </div>
        <div class="tahun">
            <select id="year-dropdown">
                <!-- Dropdown options will be generated by JavaScript -->
            </select>
        </div>
        <div class="pdf-controls" id="download-link">
        </div>
    </div>
    <div class="result">
        <ul id="search-results"></ul>
    </div>
    <div id="pdf-viewer">
        <!-- PDF will be embedded here -->
        <img style="margin-top:20px" width="100%" src="<?= base_url('public/images/beranda_ok.jpg') ?>" alt="">
    </div>

</div>

<script>
    function showPDF2(namafile, batastahun) {
        pdfFile = "<?= base_url('public/pustaka/') ?>" + batastahun + "/" + namafile + ".pdf";
        const pdfViewer = document.getElementById('pdf-viewer');
        pdfViewer.innerHTML = `<embed src="${pdfFile}" type="application/pdf" class="pdf-viewer">`;

        const downloadLink = document.getElementById('download-link');
        downloadLink.innerHTML = `<a href="${pdfFile}" download><button class="tbdownload">Download PDF</button></a>`;
    }

    function showPDF(namafile, batastahun) {
        {
            var pdfFile = "<?= base_url('public/pustaka/') ?>" + batastahun + "/" + namafile + batastahun + ".pdf";

            fetch(pdfFile, {
                    method: 'HEAD'
                })
                .then(response => {
                    if (response.ok) {
                        const pdfViewer = document.getElementById('pdf-viewer');
                        pdfViewer.innerHTML = `<embed src="${pdfFile}" type="application/pdf" class="pdf-viewer">`;

                        const downloadLink = document.getElementById('download-link');
                        downloadLink.innerHTML = `<a href="${pdfFile}" download><button class="tbdownload">Download PDF</button></a>`;
                    } else {
                        handleFileNotFound();
                    }
                })
                .catch(error => {
                    console.error('Error fetching the PDF:', error);
                    handleFileNotFound();
                });
        }
    }

    function handleFileNotFound() {
        const pdfViewer = document.getElementById('pdf-viewer');
        pdfViewer.innerHTML = `<br><p> File PDF tidak ditemukan.</p>`;

        const downloadLink = document.getElementById('download-link');
        downloadLink.innerHTML = ''; // Clear the download link
    }
</script>

<?= $this->endSection() ?>